Repository HXSecurity/DongTai-agent-java, pull requests merged in 2021-12, with the labels that each got.

#162 Closes #161 (Add CHANGELOG.md)
  .github/workflows/code-check.yml
  CHANGELOG.md
  README.md
  README_CN.md
  changes/CHANGELOG-1.1.3.md
  iast-agent/src/main/resources/iast.properties
Labels: documentation

#165 Close #164
  CHANGELOG.md
  changes/CHANGELOG-1.1.3.md
Labels: documentation

#166 Update version number
  dongtai-jakarta-api/dependency-reduced-pom.xml
  dongtai-jakarta-api/pom.xml
  dongtai-jakarta-api/src/main/java/cn/huoxian/iast/api/ResponseWrapper.java
  dongtai-servlet-api/dependency-reduced-pom.xml
  dongtai-servlet-api/pom.xml
  dongtai-servlet-api/src/main/java/cn/huoxian/iast/api/ResponseWrapper.java
  dongtai-spring-api/pom.xml
  iast-agent/dependency-reduced-pom.xml
  iast-agent/pom.xml
  iast-agent/src/main/java/com/secnium/iast/agent/Constant.java
  iast-core/dependency-reduced-pom.xml
  iast-core/pom.xml
  iast-inject/pom.xml
  pom.xml
Labels: bug

#167 Update release-agent.yml
  .github/workflows/release-agent.yml
Labels: documentation

#168 modify ci
  .github/workflows/code-check.yml
  .github/workflows/release-agent.yml
Labels: bug

#169 Closes #156
  dongtai-jakarta-api/src/main/java/cn/huoxian/iast/api/RequestWrapper.java
  dongtai-servlet-api/src/main/java/cn/huoxian/iast/api/RequestWrapper.java
  iast-core/src/main/java/com/secnium/iast/core/EngineManager.java
  iast-core/src/main/java/com/secnium/iast/core/ServiceFactory.java
  iast-core/src/main/java/com/secnium/iast/core/handler/graphy/GraphBuilder.java
  iast-core/src/main/java/com/secnium/iast/core/handler/vulscan/normal/AbstractNormalVulScan.java
  iast-core/src/main/java/com/secnium/iast/core/report/AgentQueueReport.java
  iast-core/src/main/java/com/secnium/iast/core/report/ApiReport.java
  iast-core/src/main/java/com/secnium/iast/core/report/AssestReport.java
  iast-core/src/main/java/com/secnium/iast/core/report/ErrorLogReport.java
  iast-core/src/main/java/com/secnium/iast/core/report/MethodReportSender.java
  iast-core/src/main/java/com/secnium/iast/core/report/ReportSender.java
  iast-core/src/main/java/com/secnium/iast/core/report/ReportThread.java
  iast-core/src/main/java/com/secnium/iast/core/report/StartUpTimeReport.java
  iast-core/src/main/java/com/secnium/iast/core/util/HttpClientUtils.java
  iast-core/src/test/java/com/secnium/iast/core/report/HeartBeatReportTest.java
  iast-core/src/test/java/com/secnium/iast/core/report/ServiceFactoryTest.java
Labels: enhancement

#183 Release 1.1.4
  .github/workflows/code-check.yml
  .github/workflows/config/.dlc.json
  .github/workflows/dead-link-checker.yaml
  .github/workflows/release-agent.yml
  .github/workflows/version_update.sh
  README.md
  README_CN.md
  changes/CHANGELOG-1.1.3.md
  dongtai-jakarta-api/dependency-reduced-pom.xml
  dongtai-jakarta-api/pom.xml
  dongtai-servlet-api/dependency-reduced-pom.xml
  dongtai-servlet-api/pom.xml
  dongtai-spring-api/pom.xml
  iast-agent/dependency-reduced-pom.xml
  iast-agent/pom.xml
  iast-agent/src/main/java/com/secnium/iast/agent/AgentLauncher.java
  iast-agent/src/main/java/com/secnium/iast/agent/IastProperties.java
  iast-agent/src/main/java/com/secnium/iast/agent/report/AgentRegisterReport.java
  iast-agent/src/main/java/com/secnium/iast/agent/util/LogUtils.java
  iast-agent/src/main/java/com/secnium/iast/agent/util/http/HttpClientUtils.java
  iast-core/dependency-reduced-pom.xml
  iast-core/pom.xml
  iast-core/src/main/java/com/secnium/iast/core/AgentEngine.java
  iast-core/src/main/java/com/secnium/iast/core/PropertyUtils.java
  iast-core/src/main/java/com/secnium/iast/core/ServiceFactory.java
  iast-core/src/main/java/com/secnium/iast/core/context/ids/GlobalIdGenerator.java
  iast-core/src/main/java/com/secnium/iast/core/engines/impl/TransformEngine.java
  iast-core/src/main/java/com/secnium/iast/core/enhance/IastClassFileTransformer.java
  iast-core/src/main/java/com/secnium/iast/core/enhance/IastClassHookPointMatcher.java
  iast-core/src/main/java/com/secnium/iast/core/enhance/plugins/PluginRegister.java
  iast-core/src/main/java/com/secnium/iast/core/enhance/plugins/autobinding/SpringAutoBindingAdapter.java
  iast-core/src/main/java/com/secnium/iast/core/enhance/plugins/hardcoded/DispatchHardcodedPlugin.java
  iast-core/src/main/java/com/secnium/iast/core/enhance/plugins/technology/DispatchTechnologyPlugin.java
  iast-core/src/main/java/com/secnium/iast/core/enhance/sca/ScaScanner.java
  iast-core/src/main/java/com/secnium/iast/core/handler/EventListenerHandlers.java
  iast-core/src/main/java/com/secnium/iast/core/handler/models/MethodEvent.java
  iast-core/src/main/java/com/secnium/iast/core/handler/vulscan/ReportConstant.java
  iast-core/src/main/java/com/secnium/iast/core/report/ErrorLogReport.java
  iast-core/src/main/java/com/secnium/iast/core/util/ConfigUtils.java
  iast-core/src/main/java/com/secnium/iast/core/util/HttpClientUtils.java
  iast-core/src/main/java/com/secnium/iast/core/util/commonUtils.java
  iast-core/src/test/java/com/secnium/iast/core/context/ids/GlobalIdGeneratorTest.java
  iast-inject/pom.xml
  pom.xml
Labels: bug, feature

#192 Closes #191
  iast-agent/src/main/resources/iast.properties
  iast-core/src/main/java/com/secnium/iast/core/enhance/IastClassFileTransformer.java
  iast-core/src/main/java/com/secnium/iast/core/enhance/sca/ScaScanner.java
  iast-core/src/main/java/com/secnium/iast/core/handler/vulscan/ReportConstant.java
  iast-core/src/main/java/com/secnium/iast/core/report/AssestReport.java
  iast-core/src/main/resources/com.secnium.iast.resources/blackurl.txt
  iast-core/src/test/java/com/secnium/iast/core/enhance/sca/ScaScanTest.java
Labels: enhancement

#200 Enhancement: fix dubbo vul check
  .github/workflows/code-check.yml
  .github/workflows/scripts/benchmark-test.sh
  .github/workflows/scripts/openrasp-test.sh
  docs/index.md
  iast-core/src/main/java/com/secnium/iast/core/EngineManager.java
  iast-core/src/main/java/com/secnium/iast/core/IastServer.java
  iast-core/src/main/java/com/secnium/iast/core/PropertyUtils.java
  iast-core/src/main/java/com/secnium/iast/core/enhance/asm/AsmMethods.java
  iast-core/src/main/java/com/secnium/iast/core/enhance/plugins/framework/dubbo/DubboAdapter.java
  iast-core/src/main/java/com/secnium/iast/core/enhance/plugins/framework/dubbo/DubboAdviceAdapter.java
  iast-core/src/main/java/com/secnium/iast/core/handler/EventListenerHandlers.java
  iast-core/src/main/java/com/secnium/iast/core/handler/controller/TrackerHelper.java
  iast-core/src/main/java/com/secnium/iast/core/handler/controller/impl/DubboImpl.java
  iast-core/src/main/java/com/secnium/iast/core/handler/graphy/GraphBuilder.java
  iast-core/src/main/java/com/secnium/iast/core/middlewarerecognition/IServer.java
  iast-core/src/main/java/com/secnium/iast/core/middlewarerecognition/PackageManager.java
  iast-core/src/main/java/com/secnium/iast/core/middlewarerecognition/ServerDetect.java
  iast-core/src/main/java/com/secnium/iast/core/middlewarerecognition/Supplier.java
  iast-core/src/main/java/com/secnium/iast/core/middlewarerecognition/glassfish/GlassFish3.java
  iast-core/src/main/java/com/secnium/iast/core/middlewarerecognition/glassfish/GlassFish4.java
  iast-core/src/main/java/com/secnium/iast/core/middlewarerecognition/jboss/JBoss.java
  iast-core/src/main/java/com/secnium/iast/core/middlewarerecognition/jboss/JBossAS.java
  iast-core/src/main/java/com/secnium/iast/core/middlewarerecognition/jboss/WildFly.java
  iast-core/src/main/java/com/secnium/iast/core/middlewarerecognition/jetty/Jetty.java
  iast-core/src/main/java/com/secnium/iast/core/middlewarerecognition/spring/Tomcat.java
  iast-core/src/main/java/com/secnium/iast/core/middlewarerecognition/tomcat/AbstractTomcat.java
  iast-core/src/main/java/com/secnium/iast/core/middlewarerecognition/tomcat/TomcatRecognition.java
  iast-core/src/main/java/com/secnium/iast/core/middlewarerecognition/tomcat/TomcatV5.java
  iast-core/src/main/java/com/secnium/iast/core/middlewarerecognition/tomcat/TomcatV6.java
  iast-core/src/main/java/com/secnium/iast/core/middlewarerecognition/tomcat/TomcatV7.java
  iast-core/src/main/java/com/secnium/iast/core/middlewarerecognition/tomcat/TomcatV8.java
  iast-core/src/main/java/com/secnium/iast/core/middlewarerecognition/tomcat/TomcatV9.java
  iast-core/src/main/java/com/secnium/iast/core/middlewarerecognition/tomcat/TomcatVersion.java
  iast-core/src/main/java/com/secnium/iast/core/middlewarerecognition/weblogic/WebLogic.java
  iast-core/src/main/java/com/secnium/iast/core/middlewarerecognition/websphere/WebSphere.java
  iast-core/src/main/java/com/secnium/iast/core/middlewarerecognition/websphere/WebSphereVersion.java
  iast-core/src/main/java/com/secnium/iast/core/threadlocalpool/BooleanThreadLocal.java
  iast-core/src/main/java/com/secnium/iast/core/threadlocalpool/IastScopeTracker.java
  iast-inject/src/main/java/java/lang/iast/inject/Injecter.java
Labels: bug, feature
