Repository HXSecurity/DongTai-agent-java, pull requests merged in 2021-07, with the labels that each got.

#66 agent发送http响应到云端
  iast-core/src/main/java/com/secnium/iast/core/handler/EventListenerHandlers.java
  iast-core/src/main/java/com/secnium/iast/core/handler/graphy/GraphBuilder.java
Labels: enhancement

#69 enhancement 增加响应头/响应体的发送
  iast-agent/src/main/java/com/secnium/iast/agent/UpdateUtils.java
  iast-agent/src/main/java/com/secnium/iast/agent/manager/EngineManager.java
  iast-core/src/main/java/com/secnium/iast/core/EngineManager.java
  iast-core/src/main/java/com/secnium/iast/core/enhance/asm/AsmMethods.java
  iast-core/src/main/java/com/secnium/iast/core/enhance/asm/SpyUtils.java
  iast-core/src/main/java/com/secnium/iast/core/enhance/plugins/framework/j2ee/dispatch/ServletDispatcherAdviceAdapter.java
  iast-core/src/main/java/com/secnium/iast/core/handler/EventListenerHandlers.java
  iast-core/src/main/java/com/secnium/iast/core/handler/controller/impl/HttpImpl.java
  iast-core/src/main/java/com/secnium/iast/core/handler/graphy/GraphBuilder.java
  iast-core/src/main/java/com/secnium/iast/core/handler/vulscan/normal/AbstractNormalVulScan.java
  iast-core/src/main/java/com/secnium/iast/core/handler/vulscan/normal/CookieFlagsMissingVulScan.java
  iast-core/src/main/java/com/secnium/iast/core/util/HttpClientUtils.java
  iast-core/src/test/java/com/secnium/iast/core/handler/controller/impl/HttpImplTest.java
  iast-inject/src/main/java/java/lang/iast/inject/Injecter.java
  iast-servlet/pom.xml
  iast-servlet/src/main/java/cn/huoxian/iast/servlet/HttpResponse.java
  pom.xml
Labels: enhancement

#78 Optimize the data collected by the Java probe
  iast-agent/src/main/java/com/secnium/iast/agent/UpdateUtils.java
  iast-agent/src/main/java/com/secnium/iast/agent/manager/EngineManager.java
  iast-agent/src/main/java/com/secnium/iast/agent/monitor/MonitorDaemonThread.java
  iast-agent/src/main/java/com/secnium/iast/agent/monitor/UpdateMonitor.java
  iast-agent/src/test/java/com/secnium/iast/agent/UpdateUtilsTest.java
  iast-core/dependency-reduced-pom.xml
  iast-core/pom.xml
  iast-core/src/main/java/com/secnium/iast/core/enhance/IastClassFileTransformer.java
  iast-core/src/main/java/com/secnium/iast/core/enhance/IastContext.java
  iast-core/src/main/java/com/secnium/iast/core/enhance/asm/AsmMethods.java
  iast-core/src/main/java/com/secnium/iast/core/enhance/asm/SpyUtils.java
  iast-core/src/main/java/com/secnium/iast/core/enhance/plugins/AbstractAdviceAdapter.java
  iast-core/src/main/java/com/secnium/iast/core/enhance/plugins/PluginRegister.java
  iast-core/src/main/java/com/secnium/iast/core/enhance/plugins/cookie/BaseType.java
  iast-core/src/main/java/com/secnium/iast/core/enhance/plugins/framework/dubbo/DubboAdapter.java
  iast-core/src/main/java/com/secnium/iast/core/enhance/plugins/framework/j2ee/dispatch/ServletDispatcherAdapter.java
  iast-core/src/main/java/com/secnium/iast/core/enhance/plugins/framework/tomcat/DispatchRecyclePlugin.java
  iast-core/src/main/java/com/secnium/iast/core/handler/EventListenerHandlers.java
  iast-core/src/main/java/com/secnium/iast/core/handler/controller/impl/SourceImpl.java
  iast-core/src/main/java/com/secnium/iast/core/handler/graphy/GraphBuilder.java
  iast-core/src/main/java/com/secnium/iast/core/handler/graphy/GraphNode.java
  iast-core/src/main/java/com/secnium/iast/core/handler/models/MethodEvent.java
  iast-core/src/main/java/com/secnium/iast/core/handler/vulscan/ScannerFactory.java
  iast-inject/src/main/java/java/lang/iast/inject/Injecter.java
  pom.xml
Labels: bug

#79 Update README.
  README.md
  README_CN.md
Labels: documentation
